[application]
name = "Rusty Budgets"
version = "0.0.1"
[bundle]
publisher = "Kid VHS Enterprises"
# The list of files to include in the bundle. These can contain globs.
resources = ["**/*.css", "**/*.svg"]
identifier ="com.kidvhs.rusty_budgets"