services:
  rusty-budgets:
    build: .
    volumes:
      - /home/tommie/projects/rusty-budgets/data.json:/app/data/data.json
    environment:
      DATA_FILE: /app/data/data.json
    container_name: rusty-budgets
    ports:
      - 8666:8666/tcp
    restart: unless-stopped
