[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { features= ["router", "fullstack"], workspace = true }
dioxus-primitives = { workspace = true }
api = { workspace = true }
uuid = { version = "1.18.1", features = ["v4"] }
strum = { workspace = true }
#open = "5.3.2"
